name: ci

on: [push, pull_request]

jobs:
  TestWindowsRelease:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: scripts\windows\release_test.bat
        shell: cmd

  TestWindowsDebug:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: scripts\windows\debug_test.bat
        shell: cmd

  TestMac:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Install ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Test
        run: ./scripts/macos_linux/debug_test.sh

  TestUbuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Test
        run: ./scripts/macos_linux/debug_test.sh
