name: ci

on: [push, pull_request]

jobs:
  TestMac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Check available updates
        run: softwareupdate --list
        shell: bash

      - name: Update Apple Clang
        run: softwareupdate --all --install --force
        shell: bash

      - name: Test
        run: ./scripts/debug_test.sh
        shell: bash

  TestUbuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Test
        run: ./scripts/debug_test.sh
        shell: bash
